Repository oslomet-arx-as-a-service/ARXaaS, pull requests merged in 2019-04, with the labels that each got.

#101 Update READMEHTTPS.md
  READMEHTTPS.md
Labels: documentation

#108 ADD jacoco excludes configuration
  pom.xml
Labels: enhancement

#109 Refactor "static public" to "public static"
  src/main/java/no/oslomet/aaas/model/AnonymizationMetrics.java
Labels: refactor

#110 Refactor jacoco exclude settings to work properly
  pom.xml
Labels: refactor

#111 Bug fix/attribute type
  src/main/java/no/oslomet/aaas/anonymizer/ARXAnonymizer.java
  src/main/java/no/oslomet/aaas/model/AnonymizeResult.java
  src/test/java/no/oslomet/aaas/anonymizer/ARXAnonymizerTest.java
Labels: enhancement

#117 Docs/spring rest docs
  .travis.yml
  pom.xml
  src/main/asciidoc/index.adoc
  src/test/java/no/oslomet/aaas/controller/ApiDocsGenerationTest.java
Labels: documentation

#118 Fix JavaDoc fails parsing javadoc tags
  .travis.yml
  src/main/java/no/oslomet/aaas/config/SecurityConfig.java
  src/main/java/no/oslomet/aaas/model/AnonymizationMetrics.java
Labels: bug

#119 Fix importing key error in before_deploy step by removing caching
  .travis.yml
Labels: bug

#120 Bugfix/key import
  .travis.yml
  maven_deploy.sh
Labels: bug

#114 ADD unit test for data content correctness for analyze integration test
  src/main/java/no/oslomet/aaas/model/AnonymizationMetrics.java
  src/test/java/no/oslomet/aaas/GenerateIntegrationTestData.java
  src/test/java/no/oslomet/aaas/controller/AnalyzationControllerTest.java
  src/test/java/no/oslomet/aaas/controller/AnonymizationIntegrationTest.java
Labels: enhancement

#124 Integration test/anonymization controller
  src/main/java/no/oslomet/aaas/model/AnonymizationMetrics.java
  src/test/java/no/oslomet/aaas/GenerateIntegrationTestData.java
  src/test/java/no/oslomet/aaas/controller/AnonymizationIntegrationTest.java
Labels: enhancement

#125 ADD jacoco settings to exclude interface classes from test coverage
  pom.xml
Labels: enhancement

#126 ADD integration test into own class from controller test class
  src/test/java/no/oslomet/aaas/controller/AnalyzationControllerTest.java
  src/test/java/no/oslomet/aaas/controller/AnalyzationIntegrationTest.java
  src/test/java/no/oslomet/aaas/controller/AnonymizationControllerTest.java
  src/test/java/no/oslomet/aaas/controller/AnonymizationEdgeCaseTest.java
  src/test/java/no/oslomet/aaas/controller/AnonymizationIntegrationTest.java
Labels: enhancement

#130 Fix typo
  Jenkinsfile
Labels: bug

#129 Test/edge case test anonymiation
  src/main/java/no/oslomet/aaas/anonymizer/ARXAnonymizer.java
  src/main/java/no/oslomet/aaas/controller/GlobalControllerExceptionHandler.java
  src/main/java/no/oslomet/aaas/exception/UnableToAnonymizeDataInvalidDataSetException.java
  src/test/java/no/oslomet/aaas/GenerateEdgeCaseData.java
  src/test/java/no/oslomet/aaas/controller/AnonymizationEdgeCaseTest.java
Labels: enhancement

#133 Update nais.yaml
  nais.yaml
Labels: enhancement

#131 ADD edge case test for analyzing with null data
  src/test/java/no/oslomet/aaas/GenerateEdgeCaseData.java
  src/test/java/no/oslomet/aaas/GenerateTestData.java
  src/test/java/no/oslomet/aaas/controller/AnalyzationEdgeCaseTest.java
  src/test/java/no/oslomet/aaas/controller/AnonymizationEdgeCaseTest.java
Labels: enhancement

#132 ADD Introduction taken from the project description.
  src/main/asciidoc/index.adoc
Labels: documentation

#136 UpdateRepo link
  Jenkinsfile
Labels: bug

#135 ADD steps on how to run docker image
  README.md
Labels: documentation

#146 Fix error where dockerfile cant find jar
  Dockerfile
Labels: bug

#149 REFACTOR removed ConfigureAnonymzer method
  src/main/java/no/oslomet/aaas/anonymizer/ARXAnonymizer.java
Labels: refactor

#142 Feature/hierarchy builder
  src/main/asciidoc/index.adoc
  src/main/java/no/oslomet/aaas/controller/HierarchyController.java
  src/main/java/no/oslomet/aaas/model/hierarchy/Hierarchy.java
  src/main/java/no/oslomet/aaas/model/hierarchy/HierarchyBuilder.java
  src/main/java/no/oslomet/aaas/model/hierarchy/HierarchyRequest.java
  src/main/java/no/oslomet/aaas/model/hierarchy/Level.java
  src/main/java/no/oslomet/aaas/model/hierarchy/OrderBasedHierarchyBuilder.java
  src/main/java/no/oslomet/aaas/model/hierarchy/RedactionBasedHierarchyBuilder.java
  src/main/java/no/oslomet/aaas/model/hierarchy/interval/Interval.java
  src/main/java/no/oslomet/aaas/model/hierarchy/interval/IntervalBasedHierarchyBuilder.java
  src/main/java/no/oslomet/aaas/model/hierarchy/interval/Range.java
  src/main/java/no/oslomet/aaas/service/HierarchyService.java
  src/test/java/no/oslomet/aaas/arx/HierarchyBuilderIntervalBasedTest.java
  src/test/java/no/oslomet/aaas/arx/HierarchyBuilderOrderBasedTest.java
  src/test/java/no/oslomet/aaas/controller/ApiDocsGenerationTest.java
  src/test/java/no/oslomet/aaas/controller/HierarchyControllerTest.java
  src/test/java/no/oslomet/aaas/hierarchies/ARXHierarchyTest.java
  src/test/java/no/oslomet/aaas/model/hierarchy/HierarchyTestUtils.java
  src/test/java/no/oslomet/aaas/model/hierarchy/OrderBasedHierarchyBuilderTest.java
  src/test/java/no/oslomet/aaas/model/hierarchy/interval/IntervalBasedHierarchyBuilderTest.java
Labels: enhancement

#153 Update version number to release to maven
  pom.xml
Labels: enhancement

#154 Refactor/re structure model packages
  src/main/java/no/oslomet/aaas/analyzer/ARXAnalyzer.java
  src/main/java/no/oslomet/aaas/analyzer/ARXReIdentificationRiskFactory.java
  src/main/java/no/oslomet/aaas/analyzer/Analyzer.java
  src/main/java/no/oslomet/aaas/anonymizer/ARXAnonymizer.java
  src/main/java/no/oslomet/aaas/anonymizer/Anonymizer.java
  src/main/java/no/oslomet/aaas/controller/AnalyzationController.java
  src/main/java/no/oslomet/aaas/controller/AnonymizationController.java
  src/main/java/no/oslomet/aaas/model/Request.java
  src/main/java/no/oslomet/aaas/model/anonymity/Anonymity.java
  src/main/java/no/oslomet/aaas/model/anonymity/AnonymizationMetrics.java
  src/main/java/no/oslomet/aaas/model/anonymity/AnonymizationResultPayload.java
  src/main/java/no/oslomet/aaas/model/anonymity/AnonymizeResult.java
  src/main/java/no/oslomet/aaas/model/anonymity/PrivacyCriterionModel.java
  src/main/java/no/oslomet/aaas/model/risk/DistributionOfRisk.java
  src/main/java/no/oslomet/aaas/model/risk/ReIdentificationRisk.java
  src/main/java/no/oslomet/aaas/model/risk/RiskProfile.java
  src/main/java/no/oslomet/aaas/service/AnalyzationService.java
  src/main/java/no/oslomet/aaas/service/AnonymizationService.java
  src/main/java/no/oslomet/aaas/service/LoggerService.java
  src/main/java/no/oslomet/aaas/utils/ARXConfigurationFactory.java
  src/main/java/no/oslomet/aaas/utils/ARXPrivacyCriterionFactory.java
  src/main/java/no/oslomet/aaas/utils/ConfigurationFactory.java
  src/test/java/no/oslomet/aaas/GenerateEdgeCaseData.java
  src/test/java/no/oslomet/aaas/GenerateIntegrationTestData.java
  src/test/java/no/oslomet/aaas/GenerateTestData.java
  src/test/java/no/oslomet/aaas/analyzer/ARXReIdentificationRiskFactoryTest.java
  src/test/java/no/oslomet/aaas/anonymizer/ARXAnonymizerTest.java
  src/test/java/no/oslomet/aaas/arx/AnalyzeAttributesTest.java
  src/test/java/no/oslomet/aaas/controller/AnalyzationControllerTest.java
  src/test/java/no/oslomet/aaas/controller/AnalyzationIntegrationTest.java
  src/test/java/no/oslomet/aaas/controller/AnonymizationControllerTest.java
  src/test/java/no/oslomet/aaas/controller/AnonymizationEdgeCaseTest.java
  src/test/java/no/oslomet/aaas/controller/AnonymizationIntegrationTest.java
  src/test/java/no/oslomet/aaas/model/AnonymizationMetricsTest.java
  src/test/java/no/oslomet/aaas/model/risk/DistributionOfRiskTest.java
  src/test/java/no/oslomet/aaas/model/risk/ReIdentificationRiskTest.java
  src/test/java/no/oslomet/aaas/model/risk/RiskProfileTest.java
  src/test/java/no/oslomet/aaas/service/AnalyzationServiceTest.java
  src/test/java/no/oslomet/aaas/service/AnonymizationServiceTest.java
  src/test/java/no/oslomet/aaas/utils/ARXPrivacyCriterionFactoryTest.java
Labels: refactor

#151 Feature/supression limit
  src/main/java/no/oslomet/aaas/anonymizer/ARXAnonymizer.java
  src/main/java/no/oslomet/aaas/model/Request.java
  src/main/java/no/oslomet/aaas/service/AnonymizationService.java
  src/main/java/no/oslomet/aaas/utils/ARXConfigurationFactory.java
  src/main/java/no/oslomet/aaas/utils/ConfigurationFactory.java
  src/test/java/no/oslomet/aaas/GenerateEdgeCaseData.java
  src/test/java/no/oslomet/aaas/GenerateIntegrationTestData.java
  src/test/java/no/oslomet/aaas/GenerateTestData.java
  src/test/java/no/oslomet/aaas/arx/AnalyzeDistributionOfRiskTest.java
  src/test/java/no/oslomet/aaas/controller/ApiDocsGenerationTest.java
  src/test/java/no/oslomet/aaas/utils/ARXConfigurationFactoryTest.java
  src/test/java/no/oslomet/aaas/utils/ARXDataFactoryTest.java
Labels: enhancement

#159 Feature/re identifactation of risk measures as double
  src/main/java/no/oslomet/aaas/analyzer/ARXAnalyzer.java
  src/main/java/no/oslomet/aaas/analyzer/ARXReIdentificationRiskFactory.java
  src/main/java/no/oslomet/aaas/model/risk/AttackerSuccess.java
  src/main/java/no/oslomet/aaas/model/risk/ReIdentificationRisk.java
  src/test/java/no/oslomet/aaas/GenerateIntegrationTestData.java
  src/test/java/no/oslomet/aaas/GenerateTestData.java
  src/test/java/no/oslomet/aaas/analyzer/ARXReIdentificationRiskFactoryTest.java
  src/test/java/no/oslomet/aaas/controller/AnalyzationIntegrationTest.java
  src/test/java/no/oslomet/aaas/model/risk/AttackerSuccessTest.java
  src/test/java/no/oslomet/aaas/model/risk/ReIdentificationRiskTest.java
  src/test/java/no/oslomet/aaas/service/AnonymizationServiceTest.java
Labels: enhancement

#156 ADD logging of suppression limit on request recieve
  src/main/java/no/oslomet/aaas/service/LoggerService.java
Labels: enhancement

#158 Refactor/log
  src/main/java/no/oslomet/aaas/service/LoggerService.java
Labels: refactor

#162 UNITtest for getters for attackersuccessrate, quasi-identifiers, popu…
  src/test/java/no/oslomet/aaas/controller/AnalyzationIntegrationTest.java
  src/test/java/no/oslomet/aaas/model/risk/AttackerSuccessTest.java
  src/test/java/no/oslomet/aaas/model/risk/ReIdentificationRiskTest.java
  src/test/java/no/oslomet/aaas/service/AnonymizationServiceTest.java
Labels: enhancement

#165 ADD field in IntervalHierarchyBuilder for column datatype
  src/main/java/no/oslomet/aaas/controller/HierarchyController.java
  src/main/java/no/oslomet/aaas/model/hierarchy/HierarchyRequest.java
  src/main/java/no/oslomet/aaas/model/hierarchy/Level.java
  src/main/java/no/oslomet/aaas/model/hierarchy/OrderBasedHierarchyBuilder.java
  src/main/java/no/oslomet/aaas/model/hierarchy/RedactionBasedHierarchyBuilder.java
  src/main/java/no/oslomet/aaas/model/hierarchy/interval/Interval.java
  src/main/java/no/oslomet/aaas/model/hierarchy/interval/IntervalBasedHierarchyBuilder.java
  src/main/java/no/oslomet/aaas/model/hierarchy/interval/Range.java
  src/test/java/no/oslomet/aaas/controller/ApiDocsGenerationTest.java
  src/test/java/no/oslomet/aaas/controller/HierarchyControllerTest.java
  src/test/java/no/oslomet/aaas/model/hierarchy/interval/IntervalBasedHierarchyBuilderTest.java
Labels: enhancement

#166 Refactor/arx anonymizer methods
  src/main/java/no/oslomet/aaas/anonymizer/ARXAnonymizer.java
  src/main/java/no/oslomet/aaas/anonymizer/Anonymizer.java
  src/main/java/no/oslomet/aaas/controller/GlobalControllerExceptionHandler.java
Labels: refactor

#168 add edge case for suppression limit, value with lesser than 0 and gre…
  src/test/java/no/oslomet/aaas/GenerateEdgeCaseData.java
  src/test/java/no/oslomet/aaas/controller/AnonymizationEdgeCaseTest.java
Labels: enhancement
