Repository oslomet-arx-as-a-service/ARXaaS, pull requests merged in 2019-03, with the labels that each got.

#55 Refactor/unittest no longer assert strings
  src/main/java/no/oslomet/aaas/utils/ARXPayloadAnalyser.java
  src/test/java/no/oslomet/aaas/service/AnalysationServiceTest.java
  src/test/java/no/oslomet/aaas/service/AnonymizationServiceTest.java
Labels: enhancement

#56 Documentation/updated javadoc for the refactored classes and methods
  src/main/java/no/oslomet/aaas/model/AnalysationPayload.java
  src/main/java/no/oslomet/aaas/model/AnonymizationPayload.java
  src/main/java/no/oslomet/aaas/model/AnonymizeResult.java
  src/main/java/no/oslomet/aaas/utils/ARXDataFactory.java
  src/main/java/no/oslomet/aaas/utils/ARXPrivacyCriterionFactory.java
  src/main/java/no/oslomet/aaas/utils/ConfigurationFactory.java
  src/main/java/no/oslomet/aaas/utils/DataFactory.java
Labels: documentation

#58 Feature/restructure payload in line with pyaaas
  src/main/java/no/oslomet/aaas/analyser/ARXAnalyser.java
  src/main/java/no/oslomet/aaas/analyser/Analyser.java
  src/main/java/no/oslomet/aaas/anonymizer/ARXAnonymiser.java
  src/main/java/no/oslomet/aaas/anonymizer/Anonymiser.java
  src/main/java/no/oslomet/aaas/controller/AnalysationController.java
  src/main/java/no/oslomet/aaas/controller/AnonymizationController.java
  src/main/java/no/oslomet/aaas/model/Attribute.java
  src/main/java/no/oslomet/aaas/model/PrivacyModelModel.java
  src/main/java/no/oslomet/aaas/model/Request.java
  src/main/java/no/oslomet/aaas/service/AnalysationService.java
  src/main/java/no/oslomet/aaas/service/AnonymizationService.java
  src/main/java/no/oslomet/aaas/utils/ARXConfigurationFactory.java
  src/main/java/no/oslomet/aaas/utils/ARXDataFactory.java
  src/main/java/no/oslomet/aaas/utils/ConfigurationFactory.java
  src/main/java/no/oslomet/aaas/utils/DataFactory.java
  src/test/java/no/oslomet/aaas/GenerateTestData.java
  src/test/java/no/oslomet/aaas/analyser/ARXAnalyserTest.java
  src/test/java/no/oslomet/aaas/anonymizer/ARXAnonymiserTest.java
  src/test/java/no/oslomet/aaas/controller/AnonymizationIntegrationTest.java
  src/test/java/no/oslomet/aaas/service/AnalysationServiceTest.java
  src/test/java/no/oslomet/aaas/service/AnonymizationServiceTest.java
  src/test/java/no/oslomet/aaas/utils/ARXPrivacyModelModelFactoryTest.java
Labels: enhancement

#59 Refactor/remove unused models and fully implement request model
  src/main/java/no/oslomet/aaas/analyser/Analyser.java
  src/main/java/no/oslomet/aaas/anonymizer/ARXAnonymiser.java
  src/main/java/no/oslomet/aaas/anonymizer/Anonymiser.java
  src/main/java/no/oslomet/aaas/controller/AnalysationController.java
  src/main/java/no/oslomet/aaas/controller/AnonymizationController.java
  src/main/java/no/oslomet/aaas/model/AnalysationPayload.java
  src/main/java/no/oslomet/aaas/model/AnonymizationPayload.java
  src/main/java/no/oslomet/aaas/model/AnonymizeResult.java
  src/main/java/no/oslomet/aaas/model/MetaData.java
  src/main/java/no/oslomet/aaas/utils/ARXConfigurationFactory.java
  src/main/java/no/oslomet/aaas/utils/ARXDataFactory.java
  src/main/java/no/oslomet/aaas/utils/ConfigurationFactory.java
  src/main/java/no/oslomet/aaas/utils/DataFactory.java
  src/test/java/no/oslomet/aaas/GenerateTestData.java
  src/test/java/no/oslomet/aaas/analyser/ARXAnalyserTest.java
  src/test/java/no/oslomet/aaas/anonymizer/ARXAnonymiserTest.java
  src/test/java/no/oslomet/aaas/controller/AnonymizationIntegrationTest.java
  src/test/java/no/oslomet/aaas/service/AnalysationServiceTest.java
  src/test/java/no/oslomet/aaas/service/AnonymizationServiceTest.java
  src/test/java/no/oslomet/aaas/utils/ARXConfigurationFactoryTest.java
  src/test/java/no/oslomet/aaas/utils/ARXDataFactoryTest.java
  src/test/java/no/oslomet/aaas/utils/ARXPrivacyModelModelFactoryTest.java
Labels: enhancement

#67 Feature/richer analysis
  src/main/java/no/oslomet/aaas/analyser/ARXAnalyser.java
  src/main/java/no/oslomet/aaas/model/AnalysisResult.java
  src/main/java/no/oslomet/aaas/model/DistributionOfRisk.java
  src/main/java/no/oslomet/aaas/model/RiskInterval.java
  src/main/java/no/oslomet/aaas/utils/ARXPayloadAnalyser.java
  src/test/java/no/oslomet/aaas/GenerateTestData.java
  src/test/java/no/oslomet/aaas/arx/AnalyzeDistributionOfRiskTest.java
  src/test/java/no/oslomet/aaas/controller/AnalysationControllerTest.java
  src/test/java/no/oslomet/aaas/model/DistributionOfRiskTest.java
  src/test/java/no/oslomet/aaas/utils/ARXConfigurationFactoryTest.java
  src/test/java/no/oslomet/aaas/utils/ARXPayloadAnalyserTest.java
Labels: enhancement

#71 Feature/add swagger support
  pom.xml
  src/main/java/no/oslomet/aaas/swagger/SwaggerConfig.java
Labels: documentation

#74 ADD methods for getting attacker success rate for prosecutor,journlis…
  src/main/java/no/oslomet/aaas/analyzer/ARXAnalyzer.java
  src/main/java/no/oslomet/aaas/utils/ARXPayloadAnalyser.java
  src/test/java/no/oslomet/aaas/analyzer/ARXAnalyzerTest.java
  src/test/java/no/oslomet/aaas/controller/AnalyzationControllerTest.java
  src/test/java/no/oslomet/aaas/controller/AnonymizationIntegrationTest.java
  src/test/java/no/oslomet/aaas/service/AnalyzationServiceTest.java
  src/test/java/no/oslomet/aaas/service/AnonymizationServiceTest.java
  src/test/java/no/oslomet/aaas/service/LoggerAnalyzationServiceTest.java
  src/test/java/no/oslomet/aaas/service/LoggerAnonymizationServiceTest.java
  src/test/java/no/oslomet/aaas/utils/ARXPayloadAnalyzerTest.java
Labels: enhancement

#80 REMOVE Swagger config class/package and dependencies from pom
  pom.xml
  src/main/java/no/oslomet/aaas/swagger/SwaggerConfig.java
Labels: bug

#84 REFACTOR metrics to reIdentificationRisk
  src/main/java/no/oslomet/aaas/model/AnalyzeResult.java
  src/main/java/no/oslomet/aaas/service/AnonymizationService.java
  src/test/java/no/oslomet/aaas/controller/AnalyzationControllerTest.java
  src/test/java/no/oslomet/aaas/service/AnalyzationServiceTest.java
Labels: refactor

#85 Update nais.yaml
  nais.yaml
Labels: bug

#88 Bugfix/silentnull return from arx anonymizer
  src/main/java/no/oslomet/aaas/anonymizer/ARXAnonymizer.java
  src/main/java/no/oslomet/aaas/controller/GlobalControllerExceptionHandler.java
  src/main/java/no/oslomet/aaas/exception/ExceptionResponse.java
  src/test/java/no/oslomet/aaas/GenerateTestData.java
  src/test/java/no/oslomet/aaas/anonymizer/ARXAnonymizerTest.java
  src/test/java/no/oslomet/aaas/controller/AnonymizationIntegrationTest.java
Labels: bug

#93 Fix yaml_path i upload step
  Jenkinsfile
Labels: enhancement

#95 ADD defining version_path variable
  Jenkinsfile
Labels: bug

#96 stringify to dir statement
  Jenkinsfile
Labels: bug

#97 change cluster to prod cluster
  Jenkinsfile
Labels: enhancement
